name: Hello World
run-name: Hello World
on:
  push:
    branches: [master]

jobs:
  python:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: script
        run: python main.py

  node:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Node JS
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 22
          cache: "npm"
      - name: script
        run: node main.js
